# Generated by Django 6.0.4 on 2026-04-10 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(blank=True, max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_meses', models.PositiveIntegerField()),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.PositiveIntegerField()),
                ('valor_caucao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa_infracao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa_rescisao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cidade_assinatura', models.CharField(max_length=100)),
                ('estado_assinatura', models.CharField(max_length=2)),
                ('data_inicio', models.DateField()),
                ('data_assinatura', models.DateField()),
                ('sem_caucao', models.BooleanField(default=False)),
                ('sem_multa_infracao', models.BooleanField(default=False)),
                ('sem_multa_rescisao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_inquilino', to='api.cliente')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_proprietario', to='api.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='api.imovel')),
            ],
        ),
    ]
