# Generated by Django 6.0.4 on 2026-04-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='rua',
        ),
    ]
