# Generated by Django 6.0.4 on 2026-04-14 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_endereco_cliente_rua'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contratoaluguel',
            options={'verbose_name': 'Contrato de Aluguel', 'verbose_name_plural': 'Contratos de Aluguel'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.CreateModel(
            name='ContratoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=100)),
                ('especificacao_servico', models.TextField()),
                ('atividades_contratadas', models.TextField()),
                ('motivo_contratacao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('prazo_meses', models.PositiveIntegerField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('dia_vencimento', models.PositiveIntegerField()),
                ('local_execucao', models.CharField(max_length=255)),
                ('executa_nas_dependencias', models.BooleanField(default=True)),
                ('disposicoes_seguranca', models.TextField()),
                ('multa_atraso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa_rescisao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('responsabilidade_subsidiaria', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_contratante', to='api.cliente')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_prestador', to='api.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_servico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato de Serviço',
                'verbose_name_plural': 'Contratos de Serviços',
            },
        ),
    ]
