# Generated by Django 6.0.4 on 2026-04-14 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_options_alter_contratoaluguel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoaluguel',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='contratoservico',
            name='contratante',
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(blank=True, max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
