# Generated by Django 6.0.6 on 2026-06-13 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_contratoaluguel_proprietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(
                r'^\d{3}\.?\d{3}\.?\d{3}-?\d{2}$',
                'CPF inválido.'
            )]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(
                r'^\d{3}\.?\d{3}\.?\d{3}-?\d{2}$',
                'CPF inválido.'
            )]),
        ),
    ]
