# Generated by Django 6.0.6 on 2026-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cliente_cpf_alter_perfilusuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(max_length=2, default=''),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_imovel DROP COLUMN IF EXISTS cidade_uf;",
            reverse_sql="ALTER TABLE api_imovel ADD COLUMN cidade_uf varchar(100);",
        ),
    ]
