# Generated by Django 6.0.6 on 2026-06-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cliente_cpf_alter_perfilusuario_cpf'),
    ]

    operations = [
    ]
