# Generated by Django 6.0.6 on 2026-06-14 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_corrige_imovel_cidade_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$', 'CPF inválido.')]),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$', 'CPF inválido.')]),
        ),
    ]
