# Generated by Django 6.0.6 on 2026-06-18 12:05

import api.cpf
from django.db import migrations, models


def formatar_cpfs_existentes(apps, schema_editor):
    for nome_modelo in ('Cliente', 'PerfilUsuario'):
        modelo = apps.get_model('api', nome_modelo)
        for registro in modelo.objects.only('id', 'cpf').iterator():
            formatado = api.cpf.formatar_cpf(registro.cpf)
            if formatado != registro.cpf:
                modelo.objects.filter(pk=registro.pk).update(cpf=formatado)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_perfilusuario_rg_legacy'),
    ]

    operations = [
        migrations.RunPython(formatar_cpfs_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, validators=[api.cpf.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(max_length=14, validators=[api.cpf.validar_cpf]),
        ),
    ]
