# Generated by Django 6.0.6 on 2026-06-18 12:39

import api.telefone
from django.db import migrations, models


def padronizar_telefones_existentes(apps, schema_editor):
    for nome_modelo in ('Cliente', 'PerfilUsuario'):
        modelo = apps.get_model('api', nome_modelo)
        for registro in modelo.objects.only('id', 'telefone').iterator():
            if not registro.telefone:
                continue
            telefone = (
                api.telefone.formatar_telefone(registro.telefone)
                if api.telefone.telefone_valido(registro.telefone)
                else ''
            )
            modelo.objects.filter(pk=registro.pk).update(telefone=telefone)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cliente_cpf_alter_perfilusuario_cpf'),
    ]

    operations = [
        migrations.RunPython(padronizar_telefones_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, validators=[api.telefone.validar_telefone]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, validators=[api.telefone.validar_telefone]),
        ),
    ]
