# Generated by Django 6.0.6 on 2026-06-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_cliente_telefone_alter_perfilusuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='orgao_expedidor',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='orgao_expedidor',
        ),
    ]
