# Generated by Django 6.0.6 on 2026-06-18 16:41

from django.db import migrations, models


def normalizar_estados_civis(apps, schema_editor):
    equivalencias = {
        'solteiro': 'Solteiro(a)', 'solteira': 'Solteiro(a)', 'solteiro(a)': 'Solteiro(a)',
        'casado': 'Casado(a)', 'casada': 'Casado(a)', 'casado(a)': 'Casado(a)',
        'uniao estavel': 'União Estável', 'união estável': 'União Estável',
        'divorciado': 'Divorciado(a)', 'divorciada': 'Divorciado(a)', 'divorciado(a)': 'Divorciado(a)',
        'viuvo': 'Viúvo(a)', 'viuva': 'Viúvo(a)', 'viúvo': 'Viúvo(a)', 'viúva': 'Viúvo(a)', 'viúvo(a)': 'Viúvo(a)',
    }
    for nome_modelo in ('Cliente', 'PerfilUsuario'):
        modelo = apps.get_model('api', nome_modelo)
        for registro in modelo.objects.only('id', 'estado_civil').iterator():
            atual = (registro.estado_civil or '').strip()
            normalizado = equivalencias.get(atual.lower(), '')
            if normalizado != registro.estado_civil:
                modelo.objects.filter(pk=registro.pk).update(estado_civil=normalizado)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_cliente_orgao_expedidor_and_more'),
    ]

    operations = [
        migrations.RunPython(normalizar_estados_civis, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('União Estável', 'União Estável'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('União Estável', 'União Estável'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=20),
        ),
    ]
