# Generated by Django 6.0.6 on 2026-06-18 17:30

import api.cep
from django.db import migrations, models


def padronizar_ceps_existentes(apps, schema_editor):
    for nome_modelo in ('Cliente', 'PerfilUsuario'):
        modelo = apps.get_model('api', nome_modelo)
        for registro in modelo.objects.only('id', 'cep').iterator():
            if not registro.cep:
                continue
            cep = api.cep.formatar_cep(registro.cep) if api.cep.cep_valido(registro.cep) else ''
            modelo.objects.filter(pk=registro.pk).update(cep=cep)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cliente_complemento_imovel_complemento_and_more'),
    ]

    operations = [
        migrations.RunPython(padronizar_ceps_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[api.cep.validar_cep]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[api.cep.validar_cep]),
        ),
    ]
