# Generated by Django 6.0.6 on 2026-06-18 18:02

import api.cep
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_cliente_cep_alter_perfilusuario_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, validators=[api.cep.validar_cep]),
        ),
    ]
