# Generated by Django 6.0.6 on 2026-06-18 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_imovel_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoaluguel',
            name='dia_vencimento',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
